fix: ruff and mypy error following...
# MYPY error
sun_find_west_v2\config\utils_json.py:9: error: Cannot find implementation or library stub for module named "PATH"  [import-not-found]
sun_find_west_v2\config\utils_json.py:62: error: Function "exists" could always be true in boolean context  [truthy-function]
sun_find_west_v2\config\utils_json.py:67: error: Name "path" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:15: error: Argument 1 to "append" of "list" has incompatible type "Path"; expected "str"  [arg-type]
sun_find_west_v2\config\config_manager.py:33: error: Name "textpath" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:35: error: Cannot find implementation or library stub for module named "PATH"  [import-not-found]
sun_find_west_v2\config\config_manager.py:36: error: Cannot find implementation or library stub for module named "utils_json"  [import-not-found]
sun_find_west_v2\config\config_manager.py:37: error: Cannot find implementation or library stub for module named "cache_update"  [import-not-found]
sun_find_west_v2\config\config_manager.py:54: error: Name "CONFIG_JSON_PATH" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:54: error: Name "CONFIG_TEXT_PATH" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:94: error: Name "CONFIG_JSON_PATH" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:94: error: Name "CONFIG_TEXT_PATH" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:104: error: Name "CONFIG_JSON_PATH" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:113: error: Name "DEFAULT_JSON_PATH" is not defined  [name-defined]
sun_find_west_v2\config\config_manager.py:114: error: Name "OUTLINE_JSON_PARH" is not defined  [name-defined]
sun_find_west_v2\config\cache_update.py:4: error: Cannot find implementation or library stub for module named "utils_json"  [import-not-found]
sun_find_west_v2\config\cache_update.py:5: error: Cannot find implementation or library stub for module named "PATH"  [import-not-found]
sun_find_west_v2\config\cache_update.py:149: error: Argument 1 to "append" of "list" has incompatible type "Path"; expected "str"  [arg-type]
sun_find_west_v2\camera\controller.py:22: error: Skipping analyzing "zwoasi": module is installed, but missing library stubs or py.typed marker  [import-untyped]
sun_find_west_v2\camera\controller.py:22: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
sun_find_west_v2\main.py:82: error: Skipping analyzing "zwoasi": module is installed, but missing library stubs or py.typed marker  [import-untyped]
sun_find_west_v2\main.py:83: error: Library stubs not installed for "jsonschema"  [import-untyped]
sun_find_west_v2\main.py:83: note: Hint: "python3 -m pip install types-jsonschema"
sun_find_west_v2\main.py:83: note: (or run "mypy --install-types" to install all missing stub packages)
sun_find_west_v2\main.py:102: error: Cannot find implementation or library stub for module named "camera.controller"  [import-not-found]
sun_find_west_v2\main.py:103: error: Cannot find implementation or library stub for module named "core"  [import-not-found]
sun_find_west_v2\main.py:104: error: Cannot find implementation or library stub for module named "core.drawer"  [import-not-found]
sun_find_west_v2\main.py:105: error: Cannot find implementation or library stub for module named "core.MIN2ver2"  [import-not-found]
sun_find_west_v2\main.py:106: error: Cannot find implementation or library stub for module named "core.ransac"  [import-not-found]
sun_find_west_v2\main.py:203: error: Need type annotation for "buffer_c"  [var-annotated]
sun_find_west_v2\main.py:204: error: Need type annotation for "buffer_t"  [var-annotated]
sun_find_west_v2\core\ransac.py:20: error: Skipping analyzing "sklearn.linear_model": module is installed, but missing library stubs or py.typed marker  [import-untyped]
sun_find_west_v2\core\drawer.py:389: error: Argument 1 to "axes" has incompatible type "list[float]"; expected "tuple[float, float, float, float] | None"  [arg-type]
sun_find_west_v2\core\drawer.py:392: error: Argument 1 to "axes" has incompatible type "list[float]"; expected "tuple[float, float, float, float] | None"  [arg-type]
sun_find_west_v2\core\drawer.py:414: error: Need type annotation for "footsteps" (hint: "footsteps: list[<type>] = ...")  [var-annotated]
sun_find_west_v2\core\drawer.py:460: error: Cannot find implementation or library stub for module named "RANSAC"  [import-not-found]
sun_find_west_v2\core\MIN2ver2.py:47: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:49: error: Name "height" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:49: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:49: error: Name "width" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:253: error: Need type annotation for "lines" (hint: "lines: list[<type>] = ...")  [var-annotated]
sun_find_west_v2\core\MIN2ver2.py:256: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:257: error: Name "width" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:257: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:257: error: Name "height" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:265: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:276: error: Name "height" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:276: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:416: error: Need type annotation for "lines" (hint: "lines: list[<type>] = ...")  [var-annotated]
sun_find_west_v2\core\MIN2ver2.py:419: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:420: error: Name "width" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:420: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:420: error: Name "height" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:428: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:480: error: Name "divnum" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:484: error: Name "height" is not defined  [name-defined]
sun_find_west_v2\core\MIN2ver2.py:484: error: Name "width" is not defined  [name-defined]
Found 54 errors in 8 files (checked 13 source files)

# RUFF error
N999 Invalid module name: 'PATH'
--> sun_find_west_v2\config\PATH.py:1:1

I001 [*] Import block is un-sorted or un-formatted
 --> sun_find_west_v2\config\cache_update.py:1:1
  |
1 | / import logging
2 | | from pathlib import Path
3 | |
4 | | from utils_json import sha256_file, json_loader, json_saver
5 | | from PATH import pathes
  | |_______________________^
6 |
7 |   logger = logging.getLogger(__name__)
  |
help: Organize imports
  |
3 |
  - from utils_json import sha256_file, json_loader, json_saver
4 | from PATH import pathes
5 + from utils_json import json_loader, json_saver, sha256_file
6 |
  |

RUF010 [*] Use explicit conversion flag
  --> sun_find_west_v2\config\cache_update.py:91:40
   |
89 | def generate_configJ_configT(configpath: Path, textpath: Path) -> dict:
90 |     if not textpath.exists():
91 |         logger.error(f"file not found:{str(textpath)}")
   |                                        ^^^^^^^^^^^^^
92 |
93 |     with open(textpath, "r", encoding="utf-8") as f:
   |
help: Replace with conversion flag
   |
90 |     if not textpath.exists():
   -         logger.error(f"file not found:{str(textpath)}")
91 +         logger.error(f"file not found:{textpath!s}")
92 |
   |

I001 [*] Import block is un-sorted or un-formatted
 --> sun_find_west_v2\config\config_manager.py:2:1
  |
1 |   # part1 importing modules
2 | / import logging
3 | | import datetime
4 | | import sys
5 | | from pathlib import Path
  | |________________________^
6 |
7 |   """GUISET = False
  |
help: Organize imports
  |
1 | # part1 importing modules
2 + import datetime
3 | import logging
  - import datetime
4 | import sys
  |

DTZ005 `datetime.datetime.now()` called without a `tz` argument
  --> sun_find_west_v2\config\config_manager.py:17:35
   |
15 |     sys.path.append(CONFIG_ROOT)
16 |
17 |     logfile = Path(f"logs/config_{datetime.datetime.now().strftime('%Y-%m-%d')}.log")
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^
18 |
19 |     logging.basicConfig(
   |
help: Pass a `datetime.timezone` object to the `tz` parameter

F821 Undefined name `textpath`
  --> sun_find_west_v2\config\config_manager.py:33:40
   |
31 | if not logfile.parent.exists():
32 |     logfile.parent.mkdir(parents=True, exist_ok=True)
33 |     logger.debug(f"Created directory: {textpath.parent}")
   |                                        ^^^^^^^^
34 |
35 | from PATH import pathes
   |

I001 [*] Import block is un-sorted or un-formatted
  --> sun_find_west_v2\config\config_manager.py:35:1
   |
33 |       logger.debug(f"Created directory: {textpath.parent}")
34 |
35 | / from PATH import pathes
36 | | from utils_json import json_saver, json_loader, sha256_valid
37 | | from cache_update import generate_configJ_configT
   | |_________________________________________________^
38 |
39 |   globals().update(pathes)
   |
help: Organize imports
   |
34 |
35 + from cache_update import generate_configJ_configT
36 | from PATH import pathes
   - from utils_json import json_saver, json_loader, sha256_valid
   - from cache_update import generate_configJ_configT
37 + from utils_json import json_loader, json_saver, sha256_valid
38 |
   |

F401 [*] `utils_json.json_saver` imported but unused
  --> sun_find_west_v2\config\config_manager.py:36:24
   |
35 | from PATH import pathes
36 | from utils_json import json_saver, json_loader, sha256_valid
   |                        ^^^^^^^^^^
37 | from cache_update import generate_configJ_configT
   |
help: Remove unused import: `utils_json.json_saver`
   |
35 | from PATH import pathes
   - from utils_json import json_saver, json_loader, sha256_valid
36 + from utils_json import json_loader, sha256_valid
37 | from cache_update import generate_configJ_configT
   |

F821 Undefined name `CONFIG_JSON_PATH`
  --> sun_find_west_v2\config\config_manager.py:54:38
   |
52 |             from cache_update import generate_configJ_configT
53 |
54 |             generate_configJ_configT(CONFIG_JSON_PATH, CONFIG_TEXT_PATH)
   |                                      ^^^^^^^^^^^^^^^^
55 |     return nodiff == len(pathes)
   |

F821 Undefined name `CONFIG_TEXT_PATH`
  --> sun_find_west_v2\config\config_manager.py:54:56
   |
52 |             from cache_update import generate_configJ_configT
53 |
54 |             generate_configJ_configT(CONFIG_JSON_PATH, CONFIG_TEXT_PATH)
   |                                                        ^^^^^^^^^^^^^^^^
55 |     return nodiff == len(pathes)
   |

F821 Undefined name `CONFIG_JSON_PATH`
  --> sun_find_west_v2\config\config_manager.py:94:30
   |
92 | # text繧男son蠖｢蠑上↓螟画鋤縺励）son繝輔ぃ繧､繝ｫ繧堤函謌・93 | try:
94 |     generate_configJ_configT(CONFIG_JSON_PATH, CONFIG_TEXT_PATH)
   |                              ^^^^^^^^^^^^^^^^
95 |     logger.info("__sucessful jenelate json from text")
96 | except (KeyError, ValueError):
   |

F821 Undefined name `CONFIG_TEXT_PATH`
  --> sun_find_west_v2\config\config_manager.py:94:48
   |
92 | # text繧男son蠖｢蠑上↓螟画鋤縺励）son繝輔ぃ繧､繝ｫ繧堤函謌・93 | try:
94 |     generate_configJ_configT(CONFIG_JSON_PATH, CONFIG_TEXT_PATH)
   |                                                ^^^^^^^^^^^^^^^^
95 |     logger.info("__sucessful jenelate json from text")
96 | except (KeyError, ValueError):
   |

F821 Undefined name `CONFIG_JSON_PATH`
   --> sun_find_west_v2\config\config_manager.py:104:26
    |
102 | try:
103 |     logger.info("__loading config from json")
104 |     config = json_loader(CONFIG_JSON_PATH)
    |                          ^^^^^^^^^^^^^^^^
105 | except:
106 |     logger.error("__failed loading config from json")
    |

E722 Do not use bare `except`
   --> sun_find_west_v2\config\config_manager.py:105:1
    |
103 |     logger.info("__loading config from json")
104 |     config = json_loader(CONFIG_JSON_PATH)
105 | except:
    | ^^^^^^
106 |     logger.error("__failed loading config from json")
    |

F821 Undefined name `DEFAULT_JSON_PATH`
   --> sun_find_west_v2\config\config_manager.py:113:34
    |
111 | # default縺ｮjson縺ｨoutline繧堤ｩｺ蝓九ａ逕ｨ縺ｫ隱ｭ縺ｿ霎ｼ繧
112 | try:
113 |     default_config = json_loader(DEFAULT_JSON_PATH)
    |                                  ^^^^^^^^^^^^^^^^^
114 |     outline = json_loader(OUTLINE_JSON_PARH)
115 |     logger.info("__sucessful default_config")
    |

F821 Undefined name `OUTLINE_JSON_PARH`
   --> sun_find_west_v2\config\config_manager.py:114:27
    |
112 | try:
113 |     default_config = json_loader(DEFAULT_JSON_PATH)
114 |     outline = json_loader(OUTLINE_JSON_PARH)
    |                           ^^^^^^^^^^^^^^^^^
115 |     logger.info("__sucessful default_config")
116 | except:
    |

E722 Do not use bare `except`
   --> sun_find_west_v2\config\config_manager.py:116:1
    |
114 |     outline = json_loader(OUTLINE_JSON_PARH)
115 |     logger.info("__sucessful default_config")
116 | except:
    | ^^^^^^
117 |     logger.warn("__failed loading default_config")
    |

G010 [*] Logging statement uses `warn` instead of `warning`
   --> sun_find_west_v2\config\config_manager.py:117:12
    |
115 |     logger.info("__sucessful default_config")
116 | except:
117 |     logger.warn("__failed loading default_config")
    |            ^^^^
118 |
119 | if "__main__" == __name__:
    |
help: Convert to `warning`
    |
116 | except:
    -     logger.warn("__failed loading default_config")
117 +     logger.warning("__failed loading default_config")
118 |
    |

I001 [*] Import block is un-sorted or un-formatted
 --> sun_find_west_v2\config\utils_json.py:1:1
  |
1 | / import json
2 | | import logging
3 | | import hashlib
4 | | from pathlib import Path
5 | | from datetime import datetime, timezone
  | |_______________________________________^
6 |
7 |   logger = logging.getLogger(__name__)
  |
help: Organize imports
  |
1 + import hashlib
2 | import json
3 | import logging
  - import hashlib
4 + from datetime import datetime, timezone
5 | from pathlib import Path
  - from datetime import datetime, timezone
6 |
  |

F821 Undefined name `path`
  --> sun_find_west_v2\config\utils_json.py:67:43
   |
65 |     else:
66 |         expected = None
67 |         logger.debug(f"__hash not found :{path}")
   |                                           ^^^^
68 |     return actual == expected
   |

N999 Invalid module name: 'MIN2ver2'
--> sun_find_west_v2\core\MIN2ver2.py:1:1

RET501 [*] Do not explicitly `return None` in function if it is the only possible return value
   --> sun_find_west_v2\core\MIN2ver2.py:135:9
    |
133 |                     is_last=is_last
134 |                 )
135 |         return None
    |         ^^^^^^^^^^^
136 |
137 |     if isinstance(img_inst, str):
    |
help: Remove explicit `return None`
    |
134 |                 )
    -         return None
135 +         return
136 |
    |

F841 Local variable `img_path_str` is assigned to but never used
   --> sun_find_west_v2\core\MIN2ver2.py:165:9
    |
163 |         img_path_str = str(img_path)
164 |     else:
165 |         img_path_str = None
    |         ^^^^^^^^^^^^
166 |     # 繝・ヵ繧ｩ繝ｫ繝亥ｼ墓焚縺ｮ繝溘Η繝ｼ繧ｿ繝悶Ν蝗樣∩
167 |     if spots is None:
    |
help: Remove assignment to unused variable `img_path_str`

F841 [*] Local variable `e` is assigned to but never used
   --> sun_find_west_v2\main.py:107:23
    |
105 |     from core.MIN2ver2 import MIN2_ignore_sunspots as MIN2
106 |     from core.ransac import calculate_west_angle_robust as west_angle
107 | except ImportError as e:
    |                       ^
108 |     logger.error("Failed to import custom modules.")
109 |     logger.error(traceback.format_exc())
    |
help: Remove assignment to unused variable `e`
    |
106 |     from core.ransac import calculate_west_angle_robust as west_angle
    - except ImportError as e:
107 + except ImportError:
108 |     logger.error("Failed to import custom modules.")
    |

BLE001 Do not catch blind exception: `Exception`
   --> sun_find_west_v2\main.py:236:16
    |
234 |         try:
235 |             (cx, cy), r = MIN2(img)
236 |         except Exception as e:  # TODO:MIN2迢ｬ閾ｪ縺ｮERROR繧剃ｽ懆｣ｽ,謨ｴ逅・    |                ^^^^^^^^^
237 |             logger.warning(f"MIN2 processing error: {e}")
238 |             dropped_frames += 1
    |

Found 25 errors.
[*] 9 fixable with the `--fix` option (1 hidden fix can be enabled with the `--unsafe-fixes` option).